apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-http-hello
  annotations:
    github.com/project-slug: mamazary/go-http-hello
spec:
  type: service
  lifecycle: staging
  owner: infra
  project: atlanta
